language: r
r:
  - release
  - devel  

dist: xenial
cache:
  packages: true
  directories:
    - $HOME/.fonts

branches:
  only:
    - master
    - release
    - stable

latex: false
pandoc_version: 2.7.1

git:
  depth: 5
  submodules: false
  
repos:
  CRAN: https://cloud.r-project.org
  RForge: https://r-forge.r-project.org

env:
  global:
    - TZ="Asia/Shanghai"
    - MAKEFLAGS="-j 2"
    - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: ppa:opencpu/libgit2
    packages:
      - libgit2-dev
      - ghostscript
      - imagemagick
      - optipng
      - libnlopt-dev
      # rstan
      - g++-8
      # magick
      - libmagick++-dev      	
      # pdftools
      - libpoppler-cpp-dev
      # v8
      - libv8-dev	
      # sf
      - libudunits2-dev	
      - libproj-dev 	
      - libgeos-dev 	
      - libgdal-dev	
      # rgl
      - libcgal-dev 
      - libglu1-mesa-dev 
      - libglu1-mesa-dev 
      - libx11-dev

before_install:
  - mkdir -p ~/.R
  - echo "CXXFLAGS += -Wno-ignored-attributes" >> ~/.R/Makevars
  - echo "CXX14 = g++-8 -fPIC -flto=2" >> ~/.R/Makevars
  - echo "CXX14FLAGS = -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -Wno-unused-local-typedefs -Wno-ignored-attributes -Wno-deprecated-declarations -Wno-attributes -O3" >> ~/.R/Makevars
#  - nvm install stable
  - npm install netlify-cli -g
#  - curl -fLo /tmp/tinytex.tar.gz https://travis-bin.yihui.name/tinytex.tar.gz
#  - tar -xzf /tmp/tinytex.tar.gz -C $HOME
#  - export PATH=$HOME/.TinyTeX/bin/x86_64-linux:$PATH
#  - tlmgr install $(cat latex/TeXLive.pkgs | tr '\n' ' ') || true

before_script:
  - Rscript -e 'update.packages(lib.loc = .libPaths()[1], ask = FALSE)'

script:
  - Rscript -e 'bookdown::render_book("index.Rmd")'

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
      branch: master
    local_dir: _book
  - provider: script
    script: netlify deploy --prod --dir _book
    skip_cleanup: true
