language: r
r:
  - 3.4.4
dist: trusty
sudo: false
cache:
  packages: true
  directories:
    - _bookdown_files
    - $HOME/.npm
    - $HOME/texlive
    - $HOME/.fonts

branches:
  only:
    - master
    - release
    - stable

pandoc_version: 2.1.3

r_packages:
  - sf
#  - mxnet

git:
  depth: 5
  submodules: false
  
r_github_packages: 
  - tidyverse/ggplot2
  - leonawicz/mapmate
  - dgrtwo/gganimate
  - cosname/recharts
  - JohnCoene/echarts4r
  - rstudio/r2d3
#  - rmcelreath/rethinking
#  - rmcelreath/glmer2stan
  - renozao/RcppOctave
#  - ropensci/plotly
#  - dkahle/ggmap
#  - clauswilke/ggridges
  - JohnCoene/echarts4r

bioc_packages:
  - Rgraphviz
  - graph

repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org
  INLA: https://inla.r-inla-download.org/R/stable
  deltarho: http://packages.deltarho.org
  dmlc: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/

addons:
  apt:
    sources:
      - sourceline: ppa:opencpu/jq
      - sourceline: ppa:ubuntugis/ubuntugis-unstable
      - sourceline: ppa:jonathonf/python-2.7
      - sourceline: ppa:octave/stable
    packages:
      - ghostscript
      - imagemagick
      - optipng
      - libwebp-dev
      - libgsl0ldbl
      - dieharder
      - libdieharder3
      - libdieharder-dev
      - libpoppler-cpp-dev
      - libv8-3.14-dev
      - libprotobuf-dev 
      - protobuf-compiler
      - libjq-dev
      - libudunits2-dev
      - libproj-dev 
      - libgeos-dev 
      - libgdal-dev
      - python2.7
      - python-tk
      - octave
      - liboctave-dev
      - proj-bin 
      - libpaper-utils
      - libatlas3-base
      - libopenblas-base 
      - pstoedit

before_install:
  - sudo -H pip install numpy matplotlib # scipy bokeh colorcet
  - npm install netlify-cli -g
  - tlmgr update --all

before_script:
  - Rscript -e 'update.packages(ask = FALSE)'

script:
  - Rscript -e 'bookdown::render_book("index.Rmd", output_format = "all")'

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
      branch: master
    local_dir: _book
  - provider: script
    script: netlify deploy -t $NETLIFY_PAT
    skip_cleanup: true
