language: R
dist: trusty
sudo: required
cache:
  packages: true
  directories:
  - _bookdown_files
  - $HOME/.npm
  - $HOME/texlive
  - $HOME/.fonts

pandoc_version: 2.1.3

addons:
  apt:
    packages:
      - ghostscript
      - imagemagick
      - optipng
      - libwebp-dev
      - libgsl0ldbl
      - dieharder
      - libdieharder3
      - libdieharder-dev
      - libpoppler-cpp-dev
      - libv8-3.14-dev

before_install:
  - sudo add-apt-repository -y ppa:jonathonf/python-2.7
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes python2.7
  # install tmap dependencies
  - sudo apt-get install --yes libprotobuf-dev protobuf-compiler libv8-3.14-dev
  # install tmap dependencies; for 16.04 libjq-dev this ppa is needed:
  - sudo add-apt-repository -y ppa:opencpu/jq
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install libjq-dev
  # units/udunits2 dependency:
  - sudo apt-get install --yes libudunits2-dev
  # sf dependencies/spatial stack:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libproj-dev libgeos-dev libgdal-dev
  # latest octave
  - sudo apt-add-repository -y ppa:octave/stable
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes octave
  # monofont for code set
  - curl -o ~/.fonts/Inconsolata-Bold.ttf https://raw.githubusercontent.com/google/fonts/master/ofl/inconsolata/Inconsolata-Bold.ttf 
  - curl -o ~/.fonts/Inconsolata-Regular.ttf https://raw.githubusercontent.com/google/fonts/master/ofl/inconsolata/Inconsolata-Regular.ttf
  - fc-cache -fv ~/.fonts
  # for deploy
  - npm install netlify-cli -g
  # for pdf output
  - tlmgr update --all --self
  - tlmgr install $(cat TeXLive.pkgs | tr '\n' ' ') || true

script:
  - Rscript -e 'bookdown::render_book("index.Rmd", output_format = "all")'

deploy:
  provider: script
  script: netlify deploy -t $NETLIFY_PAT
  skip_cleanup: true
