language: r
r:
  - 3.4.4
#  - release
dist: trusty
sudo: false
cache:
  packages: true
  directories:
#    - _bookdown_files
#    - $HOME/.npm
    - $HOME/texlive
    - $HOME/.fonts

branches:
  only:
    - master
    - release
    - stable

pandoc_version: 2.2.1

git:
  depth: 5
  submodules: false
  
r_github_packages: 
  - tidyverse/ggplot2
  - leonawicz/mapmate
  - dgrtwo/gganimate
  - cosname/recharts
  - JohnCoene/echarts4r
  - rstudio/r2d3
#  - rmcelreath/rethinking
#  - rmcelreath/glmer2stan
  - renozao/RcppOctave
#  - ropensci/plotly
#  - dkahle/ggmap
#  - clauswilke/ggridges
  - JohnCoene/echarts4r

#bioc_packages:
#  - Rgraphviz
#  - graph

#r_packages: 
#  - rstan
#  - sf
#  - mxnet

repos:
  CRAN: https://cloud.r-project.org
#  ropensci: http://packages.ropensci.org
#  INLA: https://inla.r-inla-download.org/R/stable
#  deltarho: http://packages.deltarho.org
#  dmlc: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/
# Add marutter's c2d4u repository, (and rrutter for CRAN builds too)

addons:
  apt:
    sources:
      - sourceline: ppa:opencpu/jq
      - sourceline: ppa:opencpu/imagemagick
      - sourceline: ppa:ubuntugis/ubuntugis-unstable
      - sourceline: ppa:octave/stable
      - sourceline: ppa:marutter/rrutter
      - sourceline: ppa:marutter/c2d4u
    packages:
      - ghostscript
      - imagemagick
      - libmagick++-dev
      - optipng
      - libwebp-dev
      - libgsl0ldbl
      - dieharder
      - libdieharder3
      - libdieharder-dev
      - libpoppler-cpp-dev
      - libv8-dev
      - libprotobuf-dev 
      - protobuf-compiler
      - libjq-dev
      - libudunits2-dev
      - libproj-dev 
      - libgeos-dev 
      - libgdal-dev
      - python-tk
      - python-numpy
      - python-matplotlib
      - octave
      - liboctave-dev
      - proj-bin 
      - libpaper-utils
      - libatlas3-base
      - libopenblas-base 
      - pstoedit

before_install:
#  - sudo -H apt-get install r-cran-rstan
#  - sudo -H pip install numpy matplotlib # scipy bokeh colorcet
  - npm install netlify-cli -g
  - tlmgr update --all
  - tlmgr install $(cat TeXLive.pkgs | tr '\n' ' ') || true

before_script:
  - Rscript -e 'update.packages(lib.loc = .libPaths()[1], ask = FALSE)'

script:
  - Rscript -e 'bookdown::render_book("index.Rmd", output_format = "all")'

#deploy:
#  - provider: pages
#    skip_cleanup: true
#    github_token: $GITHUB_TOKEN
#    on:
#      branch: master
#    local_dir: _book
#  - provider: script
#    script: netlify deploy -t $NETLIFY_PAT
#    skip_cleanup: true

# deploy 
after_success:
  - netlify deploy -t $NETLIFY_PAT
