language: r
r:
  - 3.4.4
dist: trusty
sudo: false
cache:
  packages: true
  directories:
    - _bookdown_files
    - $HOME/.npm
    - $HOME/texlive
    - $HOME/.fonts

branches:
  only:
    - master

pandoc_version: 2.1.3
r_github_packages: tidyverse/ggplot2

addons:
  apt:
    sources:
      - sourceline: ppa:opencpu/jq
      - sourceline: ppa:ubuntugis/ubuntugis-unstable
      - sourceline: ppa:jonathonf/python-2.7
      - sourceline: ppa:octave/stable
    packages:
      - ghostscript
      - imagemagick
      - optipng
      - libreadline-dev
      - libwebp-dev
      - libgsl0ldbl
      - dieharder
      - libdieharder3
      - libdieharder-dev
      - libpoppler-cpp-dev
      - libv8-3.14-dev
      - libprotobuf-dev 
      - protobuf-compiler
      - libjq-dev
      - libudunits2-dev
      - libproj-dev 
      - libgeos-dev 
      - libgdal-dev
      - python2.7
      - python-tk
      - octave
      - proj-bin 
      - libpaper-utils
      - libatlas3-base
      - libopenblas-base 
      - pstoedit

before_install:
  - sudo -H pip install numpy matplotlib # scipy bokeh colorcet
  - npm install netlify-cli -g
  # upgrade texlive
  #- wget http://mirrors.rit.edu/CTAN/systems/texlive/tlnet/update-tlmgr-latest.sh
  #- sh update-tlmgr-latest.sh -- --upgrade
  #- tlmgr update --all --self

before_script:
  #- Rscript -e 'if(!require("devtools")) install.packages("devtools")'
  #- Rscript -e 'update.packages(ask = FALSE)'
  #- Rscript -e 'devtools::install_github("tidyverse/ggplot2")'  
  - Rscript -e 'devtools::install_github("leonawicz/mapmate")'
  - Rscript -e 'devtools::install_github("dgrtwo/gganimate")'

script:
  - Rscript -e 'bookdown::render_book("index.Rmd", output_format = "all")'

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
      branch: master
    local_dir: _book
  - provider: script
    script: netlify deploy -t $NETLIFY_PAT
    skip_cleanup: true
