language: r
r:
  - 3.4.4
  - release
dist: trusty
sudo: true
cache:
  packages: true
  directories:
    - $HOME/.fonts

branches:
  only:
    - master
    - release
    - stable

latex: false
pandoc_version: 2.3.1

git:
  depth: 5
  submodules: false
  
repos:
  CRAN: https://cloud.r-project.org
  RForge: https://r-forge.r-project.org
  INLA: https://inla.r-inla-download.org/R/stable
#  ropensci: http://packages.ropensci.org
#  deltarho: http://packages.deltarho.org

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: ppa:opencpu/jq
      - sourceline: ppa:opencpu/imagemagick
      - sourceline: ppa:ubuntugis/ubuntugis-unstable
      - sourceline: ppa:octave/stable
    packages:
      - ghostscript
      - imagemagick
      - libmagick++-dev
      - optipng
      - libwebp-dev
      - libgsl0ldbl
      - dieharder
      - libdieharder3
      - libdieharder-dev
      - libpoppler-cpp-dev
      - libv8-dev
      - libprotobuf-dev 
      - protobuf-compiler
      - libjq-dev
      - libudunits2-dev
      - libproj-dev 
      - libgeos-dev 
      - libgdal-dev
      - python-tk
      - python-numpy
      - python-matplotlib
      - octave
      - liboctave-dev
      - proj-bin 
      - libpaper-utils
      - libatlas3-base
      - libopenblas-base 
      - pstoedit
      - cargo
      - gcc-7
      - g++-7

before_install:
  - mkdir ~/.R
  - cp Makevars ~/.R
  - nvm install 8
  - nvm use 8
  - npm install netlify-cli -g
  - curl -fLo /tmp/tinytex.tar.gz https://travis-bin.yihui.name/tinytex.tar.gz
  - tar xzf /tmp/tinytex.tar.gz -C /$HOME
  - export PATH=/$HOME/.TinyTeX/bin/x86_64-linux:$PATH
  - tlmgr install $(cat latex/TeXLive.pkgs | tr '\n' ' ') || true

before_script:
  - Rscript -e 'update.packages(lib.loc = .libPaths()[1], ask = FALSE)'

script:
  - Rscript -e 'bookdown::render_book("index.Rmd", output_format = "all")'

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
      branch: master
    local_dir: _book
  - provider: script
    script: netlify deploy --prod --dir _book
    skip_cleanup: true

# deploy 
#after_success:
#  - netlify deploy --prod --dir _book
