\cleardoublepage 

# (APPENDIX) 附录 {-}

# 机器学习 or 深度学习 {#deep-learning-library}

- [RStudio/CentOS](http://192.168.132.3:8787/)
- [RStudio/Base](http://192.168.141.3:8181/)
- [RStudio/Rocker](http://192.168.99.100:8080/)
- [RStudio/Xenial](http://192.168.56.101:8383/)
- [RStudio/Fedora](http://192.168.9.3:8787/)

- [(book) Python 最佳实践指南](https://pythonguidecn.readthedocs.io/zh/latest/)
- [Python 中文文档](https://docs.python.org/zh-cn/3/)
- [NLP-Zhang Yi](http://codewithzhangyi.com/)
- [Automate the Boring Stuff with Python](https://automatetheboringstuff.com/)
- [Natural Language Processing with Python](http://www.nltk.org/book/)
- [前言 · Docker -- 从入门到实践](https://docker_practice.gitee.io/)
- [book: The caret Package](https://topepo.github.io/caret/index.html)

制作书签，首先下载安装好 python 如 minconda

```bash
git clone git@github.com:kent666a/py-chrome-bookmarks-markdown.git
python py-chrome-bookmarks-markdown.py filename.md
```

caret (Classification And Regression Training) R package that contains misc functions for training and plotting classification and regression models
https://topepo.github.io/caret

Local Interpretable Model-Agnostic Explanations (R port of original Python package)
https://github.com/thomasp85/lime

Explanations of model predictions with live and breakDown packages https://arxiv.org/abs/1804.01955

Descriptive mAchine Learning EXplanations
https://github.com/pbiecek/DALEX


deep learning from first principles in python r and octave <https://gigadom.wordpress.com>

## DMTK

[LightGBM](https://github.com/Microsoft/LightGBM/tree/master/R-package) A fast, distributed, high performance gradient boosting (GBDT, GBRT, GBM or MART) framework based on decision tree algorithms, used for ranking, classification and many other machine learning tasks.

提供了 R 包，微软的工具主要支持Windows平台和VS编译工具。顺便一提，[LightLDA](https://github.com/Microsoft/lightlda)^[第一作者为袁进辉] Scalable, fast, and lightweight system for large-scale topic modeling 大规模主题模型

微软开发仓库 <https://github.com/Microsoft>

## TensorFlow 

开发仓库 <https://github.com/tensorflow/tensorflow>

Computation using data flow graphs for scalable machine learning. TensorFlow is an open source software library for numerical computation using data flow graphs. 

RStudio 公司开发了 R 包接口 [tensorflow](https://github.com/rstudio/tensorflow) 和 [keras](https://github.com/rstudio/keras)


## Apache MXNet

开发仓库 <https://github.com/apache/incubator-mxnet>

Lightweight, Portable, Flexible Distributed/Mobile Deep Learning with Dynamic, Mutation-aware Dataflow Dep Scheduler; for Python, R, Julia, Scala, Go, Javascript and more

R 包 <https://github.com/apache/incubator-mxnet/tree/master/R-package>


## XGBoost

开发仓库 <https://github.com/dmlc/xgboost>
XGBoost is an optimized distributed gradient boosting library designed to be highly efficient, flexible and portable. It implements machine learning algorithms under the Gradient Boosting framework. XGBoost provides a parallel tree boosting (also known as GBDT, GBM) that solve many data science problems in a fast and accurate way. The same code runs on major distributed environment (Hadoop, SGE, MPI) and can solve problems beyond billions of examples.

使用文档 <http://xgboost.readthedocs.io/en/latest/>
R 包 <https://github.com/dmlc/xgboost/tree/master/R-package>
中文文档 <http://xgboost.apachecn.org/cn/latest/>

## CatBoost

CatBoost is an open-source gradient boosting on decision trees library with categorical features support out of the box for Python, R https://catboost.ai

<https://github.com/catboost/catboost>

catboost

```r
# windows 
devtools::install_url('https://github.com/catboost/catboost/releases/download/v0.6.1.1/catboost-R-Windows-0.6.1.1.tgz', args = c("--no-multiarch"))
# Ubuntu install libc6-dev first
devtools::install_github('catboost/catboost', subdir = 'catboost/R-package')
```

## xLearn

[xLearn](https://github.com/aksnzhy/xlearn) is a high performance, easy-to-use, and scalable machine learning package, which can be used to solve large-scale machine learning problems. xLearn is especially useful for solving machine learning problems on large-scale sparse data （大规模稀疏数据）, which is very common in Internet services such as online advertisement （在线广告）and recommender systems （推荐系统） in recent years. If you are the user of liblinear, libfm, or libffm, now xLearn is your another better choice.


## XLearning

开发仓库 <https://github.com/Qihoo360/XLearning> AI on Hadoop

XLearning is running on the Hadoop Yarn and has integrated deep learning frameworks such as TensorFlow, MXNet, Caffe, Theano, PyTorch, Keras, XGBoost. 

## GPflow

Gaussian processes in TensorFlow <https://github.com/GPflow/GPflow>
文档 <http://gpflow.readthedocs.io/en/latest/> 提到了 Fully Bayesian inference for generalized GP models with HMC 可以考虑与 Stan 比较性能

相关的框架 [GPflowOpt](https://github.com/GPflow/GPflowOpt) 主要在于贝叶斯框架下的优化计算，相关使用文档见 <https://gpflowopt.readthedocs.io/en/latest>

# 自然语言处理 {#Natural-Language-Processing}

## 文本分类 {#Text-Classification}

1. E-Commerce Reviews 数据集

[Shirin Glander](https://shirinsplayground.netlify.com/) Explaining Black-Box Machine Learning Models: Text classification with LIME [博客文章](https://shirinsplayground.netlify.com/2018/07/explaining_ml_models_code_text_lime/)

[Abien Fred Agarap](https://afagarap.me/) Statistical Analysis on E-Commerce Reviews, with Sentiment Classification using Bidirectional Recurrent Neural Network (RNN) 实现 keras 和 sklearn <https://github.com/AFAgarap/ecommerce-reviews-analysis>

# 书单 {#book-list}

- [Pro Git 中文第二版](https://git-scm.com/book/zh/v2) Scott Chacon, Ben Straub 著
- [Advanced R 第二版](https://adv-r.hadley.nz/) Hadley Wickham 著
- [Geocomputation with R](https://geocompr.robinlovelace.net/) Robin Lovelace, Jakub Nowosad, Jannes Muenchow 著
- [Spatial Microsimulation with R](https://spatial-microsim-book.robinlovelace.net/) Robin Lovelace and Morgane Dumont 著
- [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/) Yihui Xie, J. J. Allaire, Garrett Grolemund 著
- [bookdown: Authoring Books and Technical Documents with R Markdown](https://bookdown.org/yihui/bookdown/) Yihui Xie 著
- [blogdown: Creating Websites with R Markdown](https://bookdown.org/yihui/blogdown/) Yihui Xie, Amber Thomas, Alison Presmanes Hill 著
- [R: A Language and Environment for Statistical Computing](https://xiangyun.netlify.com/pdf/refman.pdf) The R Core Team 著
- [LaTeX2e unofficial reference manual](http://tug.ctan.org/tex-archive/info/latex2e-help-texinfo/latex2e.html) [pdf 版](https://xiangyun.netlify.com/pdf/latex2e.pdf)
- [Statistical Rethinking](http://xcelab.net/rm/statistical-rethinking/)  Richard McElreath 著
- [Regression Modeling Strategies](http://biostat.mc.vanderbilt.edu/wiki/Main/RmS) Frank E Harrell Jr 著
- [Applied Predictive Modeling](http://appliedpredictivemodeling.com/) Max Kuhn and Kjell Johnson 著
- [Forecasting: Principles and Practice](https://www.otexts.org/fpp2/) Rob J Hyndman and George Athanasopoulos 著
- [Applied Regression Analysis and Generalized Linear Models](https://socialsciences.mcmaster.ca/jfox/) 及书评 [JASA-review](https://socialsciences.mcmaster.ca/jfox/Books/Applied-Regression-2E/JASA-review.pdf) 附录、样章和书评位于目录 docs/John-Fox
- [Introduction to Data Science](https://rafalab.github.io/dsbook/) Rafael A. Irizarry 著
- [Feature Engineering and Selection: A Practical Approach for Predictive Models](http://www.feat.engineering) Max Kuhn and Kjell Johnson

# 主页 {#homepage}

- [Eugene Joh 的博客](https://incidental-ideas.org/)
- [Ilya Kashnitsky 的博客](https://ikashnitsky.github.io/)
- [Max Woolf 的博客](http://minimaxir.com/)
- [Yan Holtz 的 ggplot2 图库](https://www.r-graph-gallery.com/)
- [Jianghao Wang (王江浩)](https://jianghao.github.io)
- [Xinpeng Chen](https://chenxinpeng.github.io/)
- [Arthur Charpentier](https://freakonometrics.github.io) 法语 精算 or [Arthur Charpentier](https://freakonometrics.hypotheses.org)
- [François Husson](https://francoishusson.wordpress.com/) 多元统计分析
- [Jean-Paul Fox](http://www.jean-paulfox.com/) Bayesian response modeling
- [Julian faraway](https://farawaystatistics.wordpress.com) INLA [When Small Data beats Big Data](http://people.bath.ac.uk/jjf23/papers/smallvbig.pdf)
- [Shirin Glander](https://shirinsplayground.netlify.com/)
- [Yihui Xie](https://yihui.name/)
- [Beilei Bian](http://statsjoke.me)
- [Miao Yu](https://yufree.cn/)
- [Ce Gao](http://gaocegege.com/Blog/)
- [Lchiffon](http://langdawei.com/)
- [Nan Xiao](https://nanx.me/)
- [Xuening Zhu](https://xueningzhu.github.io/)
- [Guangchuang YU](https://guangchuangyu.github.io/)
- [Qiang Kou](http://qkou.info/)
- [Yixuan Qiu-cn](https://yixuan.cos.name/cn/) or [Yixuan Qiu-en](https://statr.me/)
- [Tao Gao](https://joegaotao.github.io/)
- [Xunmo Yang](https://tcya.xyz/)
- [Yalei Du](http://yalei.name/)
- [Junchen Feng](http://www.fengjunchen.com/)
- [Sizhe Liu](http://www.bjt.name/)
- [Liyun Chen](http://www.loyhome.com/)
- [Peng Zhao](http://www.pzhao.org/zh/)
- [Gaston Sanchez](http://www.gastonsanchez.com/)
- [Xiao-Li Meng](https://statistics.fas.harvard.edu/people/xiao-li-meng)
- [Peter J. Diggle](https://www.lancaster.ac.uk/staff/diggle/)
- [Jianqing Fan-Fudan](http://www.sds.fudan.edu.cn/wp/?p=1695)
- [Jianqing Fan](https://orfe.princeton.edu/~jqfan/index.html)
- [T. Tony Cai](http://www-stat.wharton.upenn.edu/~tcai/)
- [Runze Li's Homepage](http://personal.psu.edu/ril4/)
- [Jane-Ling's Webpage](http://www.stat.ucdavis.edu/~wang/)
- [Michael L. Stein](http://www.stat.uchicago.edu/faculty/stein.shtml)
- [Hang Li - Home](http://hangli-hl.com/index.html)
- [Xihong Lin | Harvard T.H. Chan School of Public Health](https://www.hsph.harvard.edu/xihong-lin/)
- [Committee of Presidents of Statistical Societies (COPSS)](http://community.amstat.org/copss/awards/winners)
- [Charlie Geyer's Personal Home Page](http://users.stat.umn.edu/~geyer/)
- [John Fox](https://socialsciences.mcmaster.ca/jfox/)
- [Paul Murrell](https://www.stat.auckland.ac.nz/~paul/)
- [Brian Ripley](http://www.stats.ox.ac.uk/~ripley/)
- [Benjamin M. Taylor, PhD](http://www.lancaster.ac.uk/staff/taylorb1/index.html)
- [Andy South – Researcher and R developer. Norwich, UK.](https://andysouth.github.io/)
- [Rob J Hyndman](https://robjhyndman.com/)
- [Julian Faraway](https://farawaystatistics.wordpress.com/)
- [Andrew Gelman](https://andrewgelman.com/)
- [Qiwei Yao](http://stats.lse.ac.uk/q.yao/)
- [ZHU Lixing](http://www.math.hkbu.edu.hk/~lzhu/)
- [Max Woolf](https://minimaxir.com/)
- [Marc Taylor](https://menugget.blogspot.com/)
- [Ignacio Sarmiento Barbieri](https://ignaciomsarmiento.github.io/)
- [Alexey Radul](https://alexey.radul.name/)
- [Daniel P. Martin](https://dpmartin42.github.io/)
- [Kevin Davenport](http://kldavenport.com/)
- [Roel M. Hogervorst](https://rmhogervorst.nl/cleancode/)
- [Dean Attali](https://deanattali.com/)
- [Ilyas Ustun](https://www.datacademy.co/)
- [Jim Hester](https://www.jimhester.com/)
- [Matt Dancho and Davis Vaughan](https://www.business-science.io/)
- [Eryk Walczak](https://walczak.org/)
- [Paula Moraga](https://paula-moraga.github.io/)
- [GAMLSS](https://www.gamlss.com/)
- [Daniel Lee (Stan)](http://syclik.com/)
- [Gianluca Baio](http://www.statistica.it/gianluca/)
- [Omiros](http://www.econ.upf.edu/~omiros/)
- [Yoonseo Zoh](https://zohyos7.github.io/)
- [Norm Matloff](https://matloff.wordpress.com/)
- [The Coatless Professor](https://thecoatlessprofessor.com/)
- [Liam Huang](https://liam.page/)
- [Kevin Ushey](https://kevinushey.github.io/)
- [Mark Sellors](https://blog.sellorm.com/)
- [LinOxide](https://linoxide.com/)
- [Bayesian Spectacles | Powered by JASP](https://www.bayesianspectacles.org/)
- [https://www.quicklatex.com](https://www.quicklatex.com/)
- [Home - Yongfu's Blog](https://liao961120.github.io/blog/)
- [小夏的笔记本 – 一气周流尽识万千象变，嘻笑怒骂拙守济世一心](http://xiaokai.me/)
- [Data Sel](https://data-se.netlify.com/)
- [Jan Vanhove](https://janhove.github.io/)
- [Richard D. Morey](https://richarddmorey.org/)
- [Todd W. Schneider](http://toddwschneider.com/)
- [Bruno Rodrigues](https://www.brodrigues.co/)
- [Cartesian Faith](https://cartesianfaith.com/)
- [WenSui Liu](https://statcompute.wordpress.com/about/)
- [Patrick Burns](https://www.burns-stat.com/)
- [Python 爬虫工具列表](https://mp.weixin.qq.com/s/X9NPFFTHTk62V21o63ceOA)
- [Eric Novik](https://www.generable.com/blog/)
- [Florian Hartig](https://theoreticalecology.wordpress.com/)
- [Suresh K. Gorakala](https://www.dataperspective.info/)
- [handong1587's blog - handong1587](https://handong1587.github.io/)
- [Paul Bürkner](https://paul-buerkner.github.io/)
- [Peter Ellis](http://freerangestats.info/)
- [Guy Abel](https://guyabel.com/)
- [Rasmus Bååth](http://sumsar.net/)
- [Yuling Yao](https://www.yulingyao.com/)
- [Doing Bayesian Data Analysis](https://doingbayesiandataanalysis.blogspot.com/)
- [Dustin Tran](http://dustintran.com/)
- [John MacFarlane - Home](http://johnmacfarlane.net/)


# 博客 {#blogger}

- [Yihui Xie | 谢益辉](https://yihui.name/)
- [Xiangyun Huang | 黄湘云](https://www.xiangyunhuang.com.cn/)
- [R 语言学习笔记](https://notesdown.netlify.com/)
- [统计计算与图形](https://xiangyunhuang.github.io/ISCGwR/)
- [Simply Statistics](https://simplystatistics.org/)
- [R packages](http://r-pkgs.had.co.nz/)
- [Advanced R](https://adv-r.hadley.nz/)
- [A Docker Tutorial for Beginners](https://docker-curriculum.com/)
- [Advanced Spatial Modeling with Stochastic Partial Differential Equations Using R and INLA](https://becarioprecario.bitbucket.io/spde-gitbook/index.html)
- [中国人民大学数据挖掘中心](https://rucdmc.github.io/)
- [空间数据分析与建模](https://bookdown.org/xiangyun/GeoSpatial/)
- [gen.lib.rus.ec](http://gen.lib.rus.ec/)

- [ProcessOn - 我的文件](https://www.processon.com/diagrams)
- [Stack Overflow - Where Developers Learn, Share, & Build Careers](https://stackoverflow.com/)
- [Sci-Hub: removing barriers in the way of science](https://sci-hub.tw/)
- [The Markov-chain Monte Carlo Interactive Gallery](https://chi-feng.github.io/mcmc-demo/)
- [Markov Chains: Why Walk When You Can Flow? | Elements of Evolutionary Anthropology](http://elevanth.org/blog/2017/11/28/build-a-better-markov-chain/)
- [Efficient mode jumping MCMC for Bayesian variable selection in GLMM by aliaksah](https://aliaksah.github.io/EMJMCMC2016/)
- [Typical Sets and the Curse of Dimensionality](http://mc-stan.org/users/documentation/case-studies/curse-dims.html)
- [Areal data. Lung cancer risk in Pennsylvania](https://paula-moraga.github.io/tutorial-areal-data/)
- [Geostatistical data. Malaria in The Gambia](https://paula-moraga.github.io/tutorial-geostatistical-data/)
- [NIMBLE – An R package for programming with BUGS models and compiling parts of R.](https://r-nimble.org/)
- [inlabru](https://sites.google.com/inlabru.org/inlabru/home)
- [Statistical Rethinking Resources](https://rpruim.github.io/Statistical-Rethinking/)
- [Handbook of mathematical functions](http://people.math.sfu.ca/~cbm/aands/frameindex.htm)
- [Unicode Chart](https://www.ssec.wisc.edu/~tomw/java/unicode.html)
- [https://stefvanbuuren.name/fimd/symbol-description.html](https://stefvanbuuren.name/fimd/symbol-description.html)
- [GeoSpatial Data Visualization in R](https://bhaskarvk.github.io/user2017.geodataviz/)
- [gallery.htmlwidgets.org](http://gallery.htmlwidgets.org/)
- [Data Science Lab](https://datascience.jd.com/)
- [Home - IAMG](https://www.iamg.org/)
- [Ecological Models and Data in R](http://ms.mcmaster.ca/~bolker/emdbook/)
- [CSS Layout - The position Property](https://www.w3schools.com/css/css_positioning.asp)
- [智能金融起锚：文因、数库、通联瞄准的kensho革命](https://awtmt.com/articles/3014055)
- [文因互联](http://memect.cn/)
- [北京空气质量指数AQI_PM2.5月统计历史数据_中国空气质量在线监测分析平台历史数据](https://www.aqistudy.cn/historydata/monthdata.php?city=%E5%8C%97%E4%BA%AC)
- [基于分布式容器和高性能计算的R](https://bwlewis.github.io/r-and-singularity/) R and Singularity
- [利用 R 和 OpenCPU 搭建高可用的 HTTP 服务](http://www.bjt.name/2017/04/opencpu-application)
- [Nearest Neighbor Gaussian Processes (NNGP) based models](https://github.com/LuZhangstat/NNGP_STAN) and [Case study: NNGP based models in Stan](http://mc-stan.org/users/documentation/case-studies/nngp.html)
- [Spatial Models in Stan: Intrinsic Auto-Regressive Models for Areal Data](http://mc-stan.org/users/documentation/case-studies/icar_stan.html) 空间模型之 Stan 实现 [slides](https://github.com/stan-dev/stancon_talks/blob/master/2018/Invited-Talks/Morris.pdf)
- [Conditional autoregressive models in Stan](https://github.com/mbjoseph/CARstan) [网页版](http://mc-stan.org/users/documentation/case-studies/mbjoseph-CARStan.html)
- [Bagging, the perfect solution for model instability](https://insightr.wordpress.com/2017/05/22/bagging-the-perfect-solution-for-model-instability/)
- [How Random Forests improve simple Regression Trees?](https://insightr.wordpress.com/2017/09/23/how-random-forests-improve-simple-regression-trees/)
- [Tuning xgboost in R: Part I](https://insightr.wordpress.com/2018/05/17/tuning-xgboost-in-r-part-i/)
- [Tuning xgboost in R: Part II](https://insightr.wordpress.com/2018/07/28/tuning-xgboost-in-r-part-ii/)
- [Easily Make Multi-tabbed .xlsx Files with openxlsx](https://trinkerrstuff.wordpress.com/2018/02/14/easily-make-multi-tabbed-xlsx-files-with-openxlsx/) Map 函数
- [Deep learning at rstudio::conf 2018](https://rviews.rstudio.com/2018/02/14/deep-learning-rstudio-conf-2018/) 深度学习与R语言,J.J.作为 RStudio 的 CEO 推动 tensorflow 在 R 中的使用，两个幻灯片值得好好看，J.J. 介绍 tensorflow Javier Luraschi介绍tf的部署
- netlify travis-ci blog 搭建 blogdown <https://bookdown.org/yihui/blogdown>
- [An Introduction to Spatial Econometrics in R](http://www.econ.uiuc.edu/~lab/workshop/Spatial_in_R.html) spatial econometric analysis 空间经济分析 可考虑翻译一下 <https://ignaciomsarmiento.github.io/2017/02/07/An-Introduction-to-Spatial-Econometrics-in-R>
- [Data Visualization Shiny Apps](https://ignaciomsarmiento.github.io/software.html) 数据可视化核密度估计 In this app I identify crime hotspots using a bivariate density estimation strategy
- [Putting the Macron in Māori: Accented text in R Graphics](https://www.stat.auckland.ac.nz/~paul/Reports/maori/maori.html) Paul Murrell 图形中嵌入重音字符
- [color in plot](https://www.stat.auckland.ac.nz/~paul/Talks/colour.pdf) Paul Murrell 配色
- [Using Computer Modern Fonts in R Graphics](https://www.stat.auckland.ac.nz/~paul/R/CM/CMR.html) Paul Murrell 图形中嵌入数学字体
- [Lattice Graphics](https://www.stat.auckland.ac.nz/~paul/Talks/dsc2001.pdf) Paul Murrell 介绍 Lattice Graphics
- [Association of Statisticians of American Religious Bodies (ASARB) viridis USA map](http://www.rpubs.com/cgarey/ProjectOneFinal)
- [Mapping unemployment data](http://sharpsightlabs.com/blog/map-unemployment-nov-2016/)
- [when-will-evolution-outperform-local-search](https://blog.evorithmics.org/2016/01/31/when-will-evolution-outperform-local-search/) 进化何时跑赢局部搜索 爱可可爱生活--进化如何跑赢局部搜索
- [Game of Thrones network analysis](https://shirinsplayground.netlify.com/2018/03/got_network/) 权利的游戏 网络
- [Using Git and GitHub with R, Rstudio, and R Markdown](https://github.com/jennybc/happy-git-with-r)
- [如何用Markdown写论文](http://blog.sciencenet.cn/blog-377709-1088215.html)
- [blogdown和Github搭建网站](https://aurora-mareviv.github.io/talesofr/2018/02/r-blogdown-setup-in-github-2/)
- [The R-INLA project and Bayesian computing with INLA](http://www.r-inla.org/)
- [Geographic Data Science in Python](https://data.cdrc.ac.uk/dataset/geographic-data-science-in-python)
- [Spatial](https://data.cdrc.ac.uk/)
- [r-spatial](https://www.r-spatial.org/)
- [Fast GeoSpatial Analysis in Python](http://matthewrocklin.com/blog/work/2017/09/21/accelerating-geopandas-1)
- [Spatial Data in R: New Directions](https://edzer.github.io/UseR2017/) Edzer Pebesma
- [A gentle INLA tutorial](https://www.precision-analytics.ca/blog-1/inla)


> 此节附录最后可以删掉

下面是用一段 Python 代码导出谷歌浏览器的所有书签

```bash
python py-chrome-bookmarks-markdown.py bookmarks.md
```

**Optimization**

- [Hyperparameter Optimization in H2O: Grid Search, Random Search and the Future – H2O blog](http://blog.h2o.ai/2016/06/hyperparameter-optimization-in-h2o-grid-search-random-search-and-the-future/)
- [R Optimization Test - Quantitative Finance Collector](http://www.mathfinance.cn/r-optimization-test/)
- [Research Seminar: Optimization](http://statmath.wu.ac.at/courses/optimization/)
- [Home - Statistics Views](http://www.statisticsviews.com/view/index.html)
- [Vasicek model - Wikiwand](https://www.wikiwand.com/en/Vasicek_model)
- [CIR模型Cox–Ingersoll–Ross model - Wikipedia, the free encyclopedia](https://en.wikipedia.org/wiki/Cox%E2%80%93Ingersoll%E2%80%93Ross_model)
- [BARON Software | Sahinidis](http://archimedes.cheme.cmu.edu/?q=baron)
- [竞赛列表-DataCastle大数据竞赛平台](http://www.pkbigdata.com/static_page/cmpList.html)
- [COIN-OR: Computational Infrastructure for Operations Research | Open-source Software for the Operations Research Community](https://www.coin-or.org/)
- [Portfolio Optimization in R, Part 4 | R-bloggers](https://www.r-bloggers.com/portfolio-optimization-in-r-part-4/)

**时间序列分析**

- [TensorFlow for Foreign Exchange Market: Analyzing Time-Series Data - Blog on All Things Cloud Foundry](https://blog.altoros.com/tensorflow-for-foreign-exchange-market-analyzing-time-series-data.html)
- [Predicting Heavy and Extreme Losses in Real-Time for Portfolio Holders (2) | Quant at Risk](http://www.quantatrisk.com/2015/12/06/predicting-heavy-and-extreme-losses-in-real-time-for-portfolio-holders-2/)
- [Why time series forecasts prediction intervals aren't as good as we'd hope](http://ellisp.github.io/blog/2016/12/07/arima-prediction-intervals)
- [Error, trend, seasonality - ets and its forecast model friends](http://ellisp.github.io/blog/2016/11/27/ets-friends)
- [Dual axes time series plots with various more awkward data](http://ellisp.github.io/blog/2016/08/28/dualaxes2)

**R 语言**

- [Togaware – Resources for the Data Scientist](https://togaware.com/)
- [ParallelR高性能并行计算与R语言](http://www.parallelr.com/)
- [R-Ladies global tour ](http://www.masalmon.eu/2017/10/06/globalrladiestour/)
- [R-Ladies Global – R-Ladies is a world-wide organization to promote gender diversity in the R community](http://rladies.org/)
- [Shane Lynn - Data science, analytics, and Startups](https://www.shanelynn.ie/)
- [Open Source Projects | NumFOCUS](https://www.numfocus.org/open-source-projects/)
- [DataScience+ An online community for showcasing R & Python tutorials](https://datascienceplus.com/)
- [Latest Posts – So Simple Theme](https://mmistakes.github.io/so-simple-theme/)
- [Video Tutorial of PSO implementation in MATLAB](http://yarpiz.com/440/ytea101-particle-swarm-optimization-pso-in-matlab-video-tutorial)
- [Statistics.com - Course List - Online Courses](http://www.statistics.com/course-catalog/)
- [me nugget](http://menugget.blogspot.jp/)
- [Time Series Analysis and Its Applications: With R Examples - tsa4](http://www.stat.pitt.edu/stoffer/tsa4/)
- [(code实战)机器学习方法和性能比较](http://rpubs.com/m3cinc/Benchmarking_20_Machine_Learning_Models_Accuracy_and_Speed)
- [ggplot2 – The R graph Gallery](http://www.r-graph-gallery.com/portfolio/ggplot2-package/)
- [quantumobject/docker-shiny - Docker Hub](https://hub.docker.com/r/quantumobject/docker-shiny/)
- [ggplot2绘图库](http://www.sthda.com/english/)
- [Highcharter 商业](http://jkunst.com/highcharter/)
- [john-coene.com](http://john-coene.com/)
- [Deep Learning in R – R Blog](http://www.rblog.uni-freiburg.de/2017/02/07/deep-learning-in-r/)
- [Zelig 统计推断方法合集](https://zeligproject.org/)
- [Paul Murrell's Home Page](https://www.stat.auckland.ac.nz/~paul/)
- [Data Science Accelerator for Credit Risk Prediction (Revolutions)](http://blog.revolutionanalytics.com/2017/07/credit-risk-prediction.html)
- [Credit Card Fraud Detection | Kaggle](https://www.kaggle.com/dalpozz/creditcardfraud)

**Python**

- [Jupyter Notebook Viewer](http://nbviewer.jupyter.org/)
- [Pyomo](http://www.pyomo.org/)
- [Bokeh Docs](http://bokeh.pydata.org/en/latest/)
- [NumPy Tutorial: Data analysis with Python](https://www.dataquest.io/blog/numpy-tutorial-python/)
- [scikit-learn: machine learning in Python — scikit-learn 0.18.1 documentation](http://scikit-learn.org/stable/)
- [Introduction to NumPy and Matplotlib - YouTube](https://www.youtube.com/watch?v=3Fp1zn5ao2M&feature=plcp)
- [Data Science, Analytics and Big Data discussions](https://discuss.analyticsvidhya.com/)
- [The Python Graph Gallery – Visualizing data – with Python](https://python-graph-gallery.com/)
- [Data science, data analysis, and data engineering tutorials and articles.](https://www.dataquest.io/blog/)
- [ŷhat | Image Processing with scikit-image](http://blog.yhat.com/posts/image-processing-with-scikit-image.html)

**社交网络**

- [Using the iGraph package to Analyse the Enron Corpus](http://r.prevos.net/analyse-enron-corpus/)
- [Help Us Map TrumpWorld](https://www.buzzfeed.com/johntemplon/help-us-map-trumpworld?utm_term=.rx9NY9Ldb#.ja8P4p9LY)
- [Enron Email Dataset](https://www.cs.cmu.edu/~./enron/)
- [Statnet](http://statnet.org/)
- [Mining Twitter with R](https://sites.google.com/site/miningtwitter/)
- [graphTweets](http://john-coene.com/packages/graphTweets/)
- [Building Wordclouds in R | DataScience+](https://datascienceplus.com/building-wordclouds-in-r/)
- [API - 微博API](http://open.weibo.com/wiki/API%E6%96%87%E6%A1%A3_V2?sudaref=jianl.org&retcode=6102)
- [Introducing tidygraph](http://www.data-imaginist.com/2017/Introducing-tidygraph/)
- [Network analysis of Game of Thrones | DataScience+](https://datascienceplus.com/network-analysis-of-game-of-thrones/)
- [Using R packages and education to scale Data Science at Airbnb – Airbnb Engineering & Data Science – Medium](https://medium.com/airbnb-engineering/using-r-packages-and-education-to-scale-data-science-at-airbnb-906faa58e12d)
- [RPubs - Twitter Coverage of the ISMB/ECCB Conference 2017](http://rpubs.com/neilfws/295865)
- [UCI Network Data Repository](https://networkdata.ics.uci.edu/)

**课程**

- [DS-GA 1003: Machine Learning and Computational Statistics, Spring 2015](http://davidrosenberg.github.io/ml2015/#home)
- [卡内基梅隆大学Machine Learning课程](http://www.cs.cmu.edu/~tom/10701_sp11/hws.shtml)
- [课程列表: Deep Learning](http://eclass.cc/courselists/117_deep_learning)
- [(概率图模型-卡内基梅隆大学) Probabilistic Graphical Models](http://www.cs.cmu.edu/~epxing/Class/10708/lecture.html)
- [Learning Deep Learning课程资料大集合](http://rt.dgyblog.com/ref/ref-learning-deep-learning.html)
- [课程Theoretical Machine Learning](http://www.cs.princeton.edu/courses/archive/spring14/cos511/schedule.html)
- [机器学习算法观](http://people.csail.mit.edu/moitra/409.html)
- [(伯克利大学)机器学习导论课程Introduction to Machine Learning](http://www.cs.berkeley.edu/~jrs/189/)
- [Intro to Apache Spark Training - Part 3 - YouTube](https://www.youtube.com/watch?v=Cxv_ERVKYE4)
- [李宏毅深度学习(2017)_演讲•公开课_科技_bilibili_哔哩哔哩](http://www.bilibili.com/video/av9770302/)
- [1.1 《机器学习中的神经网络》为什么我们需要机器学习？_腾讯视频](https://v.qq.com/x/page/t0384c1p2em.html)
- [In-depth introduction to machine learning in 15 hours of expert videos](http://www.dataschool.io/15-hours-of-expert-machine-learning-videos/)
- [Gephi 中文教程 | Udemy](https://www.udemy.com/gephi/learn/v4/overview)

**Deep Learning**

- [PyTorch](http://pytorch.org/)
- [Caffe 2 | Caffe2](https://caffe2.ai/)
- [[福利] 深入理解 RNNs & LSTM 网络学习资料 - 简书](http://www.jianshu.com/p/c930d61e1f16?from=timeline)
- [TensorFlow中文社区-首页](http://tensorfly.cn/)
- [Deep Learning in Energy Production context (wind, gas and oil)](https://amundtveit.com/)
- [Off the convex path](http://www.offconvex.org/)
- [The Neural Network Zoo - The Asimov Institute](http://www.asimovinstitute.org/neural-network-zoo/)
- [Yann LeCun's Home Page](http://yann.lecun.com/)
- [Yoshua Bengio](http://www.iro.umontreal.ca/~bengioy/yoshua_en/index.html)
- [Ian Goodfellow --- Research Page](http://www.iangoodfellow.com/)
- [Time Series Prediction With Deep Learning in Keras - Machine Learning Mastery](http://machinelearningmastery.com/time-series-prediction-with-deep-learning-in-python-with-keras/)
- [迁移学习 Keras R](https://flovv.github.io/Logo_detection_transfer_learning/)
- [Information Systems Research](https://www.is.uni-freiburg.de/)
- [The Ultimate List of TensorFlow Resources: Books, Tutorials & More - Hacker Lists](https://hackerlists.com/tensorflow-resources/)
- [Neural Networks from Scratch, in R (Revolutions)](http://blog.revolutionanalytics.com/2017/07/nnets-from-scratch.html)
- [[机器学习入门] 李宏毅机器学习笔记](http://blog.csdn.net/soulmeetliang)
- [Center for Machine Learning and Intelligent Systems | University of California, Irvine](http://cml.ics.uci.edu/)
- [(支持向量机算法)LIBSVM -- A Library for Support Vector Machines](http://www.csie.ntu.edu.tw/~cjlin/libsvm/)

**软件测试**

- [Jenkins](https://jenkins.io/)
- [Centos | Docker中文教程](https://letong.gitbooks.io/docker/content/install/centos.html)
- [Ubuntu – Ubuntu Packages Search](https://packages.ubuntu.com/)
- [Pandoc - Pandoc User’s Guide](http://pandoc.org/MANUAL.html#pandocs-markdown)

**LaTeX**

- [始终](https://liam0205.me/)
- [风陵渡](http://wangmurong.org.cn/)
- [fitsir的博客](https://fitsir.me/)
- [Ethlisan | Ethan DENG's Personal Homepage](http://ddswhu.com/)
- [Cyberspace of Shujun LI李树钧](http://www.hooklee.com/)
- [LaTeX写作专栏 – |经常|](http://blog.feieee.com/latex)
- [在线 LaTeX 公式编辑器](http://www.codecogs.com/latex/eqneditor.php)
- [Beamer Matrix](https://mpetroff.net/files/beamer-theme-matrix/)
- [ChinaTeX-Tex&LaTeX are your typesetting friends.](http://www.chinatex.org/)
- [LaTeX Templates](http://www.latextemplates.com/)
- [Overleaf](https://www.overleaf.com/)
- [Introduction | Learning-Markdown (Markdown 入门参考)](http://xianbai.me/learn-md/index.html)
- [MathJax | Beautiful math in all browsers.](https://www.mathjax.org/)
- [Pandoc - About pandoc](https://pandoc.org/)
- [TikZ and PGF | TeXample.net](http://www.texample.net/tikz/)
- [Rants from the Lab](http://liantze.penguinattack.org/)
- [国家企业信用信息公示系统](http://www.gsxt.gov.cn/index.html)
- [Linux命令大全(手册)_Linux常用命令行实例详解_Linux命令学习手册](http://man.linuxde.net/)
- [生命不息 | 张宏伦的个人博客](http://zhanghonglun.cn/blog/)
- [大赛列表页](https://tianchi.aliyun.com/competition/gameList.htm)
- [城市数据派-首页](https://www.udparty.com/index.php)
- [研趣网 - 首个可视化商业价值挖掘和传播社区](http://www.rinterest.cn/)
- [inFERENCe](http://www.inference.vc/)
- [MSDN, 我告诉你](http://msdn.itellyou.cn/)
- [RegExr: Learn, Build, & Test RegEx](https://regexr.com/)
- [rud.is | "In God we trust. All others must bring data"](https://rud.is/b/)
- [北京理工大学 开源软件镜像服务](http://mirror.bit6.edu.cn/web/)
- [Statistics authors/titles recent submissions](http://arxiv.org/list/stat/recent)
- [Wolfram|Alpha: Computational Knowledge Engine](http://www.wolframalpha.com/?source=nav)
- [中国科技论文在线](http://www.paper.edu.cn/)
- [我是菜鸟 | IMCN开源资讯网](https://imcn.me/)
- [USGS.gov](https://www.usgs.gov/)
- [Index of /download/ensembles/data/Grid_0.44deg_rot](http://www.ecad.eu/download/ensembles/data/Grid_0.44deg_rot/)
- [The Stan Forums](http://discourse.mc-stan.org/)
- [论坛 - 六维空间 - 教育科研网分享测试平台](http://bt.neu6.edu.cn/forum.php)
- [免费在线电影-新剧集影院官网-支持手机观看](http://www.xinjuji.com/index.html)
- [CCTV-1 综合频道高清直播](http://tv.cctv.com/live/cctv1/)
- [BYR-IPTV](http://tv.byr.cn/tv-show-detail/78)
- [七牛云-国内领先的企业级云服务商](https://www.qiniu.com/)
- [RStudio Community](https://community.rstudio.com/)
- [电影天堂_免费电影_迅雷电影下载](http://www.dytt8.net/)
- [80s电影网 - 高清手机电影迅雷下载_最新MP4电视剧磁力下载](https://www.80s.tw/)
- [Google](https://www.google.com/)
- [gen.lib.rus.ec](http://gen.lib.rus.ec/)
- [Octave Online · Cloud IDE compatible with MATLAB](https://octave-online.net/#cmd=peaks)
