# Git

## 合并上流的 commit 

```bash
git clone --depth=5 https://github.com/XiangyunHuang/cosx.org.git
git submodule update --init --recursive
# 查看远程分支
cd cosx.org
git remote -v
```

```
origin  https://github.com/XiangyunHuang/cosx.org.git (fetch)
origin  https://github.com/XiangyunHuang/cosx.org.git (push)
```


```bash
# 添加上流分支
git remote add upstream https://github.com/cosname/cosx.org.git
git remote -v
```
```
origin  https://github.com/XiangyunHuang/cosx.org.git (fetch)
origin  https://github.com/XiangyunHuang/cosx.org.git (push)
upstream        https://github.com/cosname/cosx.org.git (fetch)
upstream        https://github.com/cosname/cosx.org.git (push)
```

```bash
# 获取上流 commit 并且合并到我的 master 分支
git fetch upstream
git merge upstream/master master
git push origin master
```

## 新建分支


```bash
git checkout -b stan # 新建 stan 分支
git branch -v # 查看本地分支 stan 前有个星号标记
git pull --rebase git@github.com:XiangyunHuang/cosx.org.git master
# 同步到远程分支 stan
git push --set-upstream origin stan
git push origin master:stan

git add .
git commit -m "balabala"
git push --set-upstream origin stan
```

## 创建站点

基于 GitHub Pages 创建站点用于存放图片和数据

1. 在Github上创建一个空的仓库，命名为 uploads，没有 readme.md 和 LICENSE
2. 在本地创建目录 uploads 
3. 切换到 uploads 目录下

git init 
git checkout -b gh-pages
git remote add origin https://github.com/XiangyunHuang/home.git

添加图片或者数据，并且 git add 和 commit 后

git push --set-upstream origin gh-pages

这样仓库 home 只包含 gh-pages 分支

数据地址即为

https://xiangyunhuang.github.io/home/data/eqList2018_05_18.xls

## 回车换行

CR (Carriage Return) 表示回车，LF (Line Feed) 表示换行，Windows 下用回车加换行表示下一行，UNIX/Linux 采用换行符 (LF) 表示下一行，MAC OS 则采用回车符 (CR) 表示下一行

```bash
git config --global core.autocrlf false
```

添加子模块

```bash
git submodule add git://github.com/jgm/pandoc-templates.git templates
```

克隆项目

```bash
git clone --depth=10 --branch=master --recursive \
    git@github.com:XiangyunHuang/pandoc4everything.git
```

配置账户

```bash
git config --global user.email "email"
git config --global user.name "username"
touch .git-credentials
echo "https://username:password@github.com" >> .git-credentials
git config --global credential.helper store
```

往空的 Github 仓库添加本地文件

```bash
git init
git remote add origin https://github.com/XiangyunHuang/notesdown.git
git add -A
git commit -m "balabala"
git push -u origin master
```

本地新建仓库推送至远程分支

```bash
git remote add origin https://github.com/XiangyunHuang/notesdown.git
git add .
git commit -m "init cos-art"
# 此时远程仓库 notesdown 还没有 cos-art 分支
git push origin master:cos-art
```

使用 zsh

```bash
sudo apt update && sudo apt install zsh
sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
```

位于 [Github](https://github.com/liuhui998/gitbook) [Git Community Book 中译本](http://gitbook.liuhui998.com/)


## PR 

```bash
git pull --rebase git@github.com:yihui/xaringan.git master
# then force push to your master branch
```

参考 <https://github.com/yihui/xaringan/pull/107>

> I don't recommend you to use your master branch for pull requests, because all commits will be squashed before merging, e.g. c2c2055 Then you will have some trouble with syncing your master branch with the master branch here (your choices are (1) delete your repo and fork again; or (2) force push; either option is not good). For pull requests, I recommend that you always use different branches for different pull requests.
